### PR TITLE
Edge Login React Web: Fix pin login not displaying correctly on mobil…

### PR DESCRIPTION
**Pull request by amanalili**
…e none chrome browsers

### CODE REVIEW

**Comment by paullinator** [comment]
Art, can you describe what the problem was and how you fixed it?

**Comment by amanalili** [comment]
The problem is on how you display the custom pin input with the "dots". The first code I write is that it shows a background "grey dots" and the input overlaps the dots with "password dark dots". The styles are very custom and complicated. Seems really buggy on other browsers and type of device being used. 

I corrected it by making the input text invisible, no cursor showing. And the background dots respond on how many input length already put on the input. And put a z-index for added measure to always focus the pin input if clicked or touched.

**Comment by paullinator** [comment]
Thanks for the clarification Art. I'll have @kylanhurt do a more complete review as he's more familiar with CSS

**Comment by kylanhurt** [comment]
@amanalili Unless I am not building the repo correctly it doesn't seem like PIN is working in Safari (on Mac laptop). Art, please message me when you get a chance so that we can complete these two tasks quickly.

**Pull request merged**
